stages:
  - validate-setup

validate-setup:
  stage: validate-setup
  image: debian:bookworm
  tags: ['ace-x86_64']
  variables:
    WORKSPACE: workspace
  before_script:
    - apt-get -y update &> /dev/null
    - apt-get -y install npm libarchive-tools curl git cmake ninja-build gperf ccache dfu-util device-tree-compiler wget python3-venv python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev mono-complete
    - echo "progress=dot:giga" > ${HOME}/.wgetrc
    # Setup workspace
    - ./setup.sh
    - source ${WORKSPACE}/vsd-env.sh
  script:
    # Build app on demo graph
    - vsd prepare-zephyr-board demo/stm32-led-thermometer.json
    - vsd build-zephyr demo-blinky-temp
    - vsd prepare-renode-files demo-blinky-temp

    # We expect that the simulation will succeed and run forever. In that case, timeout
    # command would kill the simulation after 20 seconds and return 124 indicating timeout.
    - timeout --signal=SIGINT 20 vsd simulate demo-blinky-temp || test $? -eq 124
  artifacts:
    paths:
      - workspace/builds/demo-blinky-temp
    when: always
  only:
    - main
    - dev
    - merge_requests
